name: Varbase AI Agents
description: Provides an AI-powered chatbot for streamlined administration and allows managing multiple agents with distinct functionalities.
type: Varbase AI
install:
  - key
  - ai
  - ai_assistant_api
  - ai_chatbot
  - ai_agents
config:
  import:
    ai_chatbot: '*'
    ai_agents: '*'
  actions:
    block.block.ai_chatbot:
      createIfNotExists:
        langcode: en
        status: true
        dependencies:
          module:
            - ai_chatbot
            - block_class
          theme:
            - gin
        id: ai_chatbot
        theme: gin
        region: content
        weight: 0
        provider: null
        plugin: ai_chatbot_block
        settings:
          id: ai_chatbot
          label: 'AI Agent'
          label_display: '0'
          provider: ai_chatbot
          ai_assistant: ai_agent_assistant
          bot_name: 'AI Agent'
          bot_image: /profiles/contrib/varbase/logo.png
          use_username: 1
          default_username: User
          use_avatar: 1
          default_avatar: /profiles/contrib/varbase/images/favicon.ico
          first_message: 'Hi! How can I assist you?'
          stream: 0
          toggle_state: remember
          output_type: markdown
          show_structured_results: true
        visibility: {  }
